server:
  port: 8090

spring:
  application:
    name: GATEWAY
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

#Registrando apigateway a eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA:http://localhost:8761/eureka}
    healthcheck:
      enabled: true
